import { useEffect, useState } from "react";
import VTuberChat from "@/pages/VTuberChat";
import "./yuki.css";
import "./yuki-redesign.css";

type Profile = { name: string; topics: string[]; birthday: string; about: string };
const defaults: Profile = { name: "", topics: [], birthday: "", about: "" };
const readProfile = (): Profile => { try { return { ...defaults, ...JSON.parse(localStorage.getItem("yuki.profile") || "{}") }; } catch { return defaults; } };
const pages = [["home","Home","⌂"],["chat","Live Call","◉"],["history","History","◷"],["memory","Memory","◇"],["settings","Settings","⚙"],["about","About","ⓘ"]];
function go(path: string) { history.pushState({}, "", `/${path}`); window.dispatchEvent(new PopStateEvent("popstate")); window.scrollTo({top:0,behavior:"smooth"}); }
function Footer() { return <footer className="yuki-footer"><div><a className="footer-brand" href="/home" onClick={e=>{e.preventDefault();go("home")}}>YUKI<span>✳</span></a><p>Personal AI assistant yang dibuat dengan penuh perhatian oleh Kevsoft Studio.</p><small>© {new Date().getFullYear()} YUKI · All rights reserved.</small></div><div className="footer-links"><b>POWERED BY KEVSOFT STUDIO</b><a href="https://github.com/kevsoftstudio" target="_blank" rel="noreferrer">GitHub ↗</a><a href="mailto:kevsoftstudio@gmail.com">Email ↗</a><a href="https://dev.to/kevsoftstudio" target="_blank" rel="noreferrer">Dev.to ↗</a><a href="https://t.me/kevsoftstudio" target="_blank" rel="noreferrer">Telegram ↗</a></div></footer>; }
const topics = ["Belajar & sekolah","Programming","Kreativitas","Produktivitas","Curhat & teman ngobrol","Teknologi","Bahasa","Hiburan"];
function Onboarding({ onDone }: { onDone: (p: Profile) => void }) {
 const [profile,setProfile] = useState<Profile>(readProfile()); const [step,setStep] = useState(0);
 const toggle=(t:string)=>setProfile(p=>({...p,topics:p.topics.includes(t)?p.topics.filter(x=>x!==t):[...p.topics,t]}));
 return <main className="onboarding"><div className="onboard-top"><button className="brand" onClick={()=>go("home")}><span className="brand-mark">✳</span><span>YUKI<small>PERSONAL AI ASSISTANT</small></span></button><span className="step-count">0{step+1} / 03</span></div><div className="onboard-content"><div className="eyebrow">A SPACE THAT KNOWS YOU</div>{step===0?<><h1>Senang bertemu<br/>denganmu<em>.</em></h1><p>Kenalan sebentar supaya YUKI bisa menemanimu dengan cara yang lebih personal.</p><label className="field-label">Kamu ingin dipanggil apa?</label><input className="yuki-input" placeholder="Nama panggilanmu" maxLength={40} value={profile.name} onChange={e=>setProfile(p=>({...p,name:e.target.value}))}/><label className="field-label">Tanggal lahir <span className="muted">· opsional</span></label><input className="yuki-input" type="date" max={new Date().toISOString().slice(0,10)} value={profile.birthday} onChange={e=>setProfile(p=>({...p,birthday:e.target.value}))}/><div className="privacy-note">◇ Profil disimpan di perangkatmu. Hindari memasukkan informasi sensitif.</div><button className="primary-btn" onClick={()=>setStep(1)}>Lanjutkan <span>↗</span></button></>:step===1?<><h1>Apa yang kamu<br/>sukai<em>?</em></h1><p>Pilih topik yang sering kamu bahas. Kamu bisa mengubahnya kapan saja.</p><div className="topic-grid">{topics.map(t=><button key={t} className={`topic-chip ${profile.topics.includes(t)?"selected":""}`} onClick={()=>toggle(t)}>{profile.topics.includes(t)?"✓":"＋"} {t}</button>)}</div><label className="field-label">Hal lain tentang kamu <span className="muted">· opsional</span></label><textarea className="yuki-input" rows={3} placeholder="Misalnya: aku suka jawaban yang singkat..." value={profile.about} onChange={e=>setProfile(p=>({...p,about:e.target.value}))}/><div className="button-row"><button className="ghost-btn" onClick={()=>setStep(0)}>Kembali</button><button className="primary-btn" onClick={()=>setStep(2)}>Lanjutkan ↗</button></div></>:<><div className="finish-orb">✳</div><h1>Ruangmu siap<em>.</em></h1><p>YUKI akan menyesuaikan obrolan dengan preferensimu. Kamu tetap bisa mengedit semuanya nanti.</p><div className="summary-card"><span>YOUR PROFILE</span><strong>{profile.name.trim()||"Teman baru"}</strong><small>{profile.topics.length?profile.topics.join(" · "):"Semua topik terbuka"}</small></div><button className="primary-btn" onClick={()=>onDone(profile)}>Mulai bersama YUKI <span>↗</span></button></>}</div><Footer/></main>
}
function Landing({profile}:{profile:Profile}) {
 const [count,setCount]=useState(0); useEffect(()=>{const onScroll=()=>setCount(window.scrollY);window.addEventListener("scroll",onScroll,{passive:true});return()=>window.removeEventListener("scroll",onScroll)},[]);
 return <div className="landing" data-scrolled={count>24}><div className="scroll-progress" style={{transform:`scaleX(${Math.min(count/Math.max(document.documentElement.scrollHeight-window.innerHeight,1),1)})`}}/><header className="landing-nav"><button className="brand" onClick={()=>go("home")}><span className="brand-mark">✳</span><span>YUKI<small>PERSONAL AI ASSISTANT</small></span></button><nav><a href="#call">Live Call</a><a href="#features">Fitur</a><a href="#how">Cara Kerja</a><a href="#experience">Pengalaman</a></nav><div className="nav-actions"><button className="profile-mini" onClick={()=>go("memory")}>{profile.name||"Profil"} ↗</button><button className="dark-btn small" onClick={()=>go("chat")}>Mulai Call <span>↗</span></button></div></header>
 <section className="landing-hero" id="top"><div className="hero-grain"/><div className="hero-copy"><div className="eyebrow"><i/> PERSONAL AI · BAHASA INDONESIA</div><h1>Teman ngobrol<br/>yang terasa <em>hidup.</em></h1><p className="lede">Temukan ruang percakapan yang tenang dan personal. Bicara dengan YUKI, assistant dari Kevsoft Studio, melalui chat, suara, dan karakter VTuber interaktif.</p><div className="hero-buttons"><button className="dark-btn" onClick={()=>go("chat")}>◉ Mulai Live Call <span>↗</span></button><a className="light-btn" href="#how">Pelajari cara kerja</a></div><div className="hero-meta"><div className="avatar-stack"><span>Y</span><span>✳</span><span>♡</span></div><div><b>Selalu siap menemani</b><small>AI personal · Konteks yang bisa kamu atur</small></div><div className="latency"><span/> Voice ready</div></div></div><div className="hero-visual"><div className="visual-glow"/><div className="portrait-card"><div className="portrait-top"><span><i/> YUKI · LIVE SESSION</span><span>01 / AI</span></div><div className="portrait-art"><div className="orbital orbital-one"/><div className="orbital orbital-two"/><div className="portrait-symbol">✳</div><div className="portrait-caption"><b>YUKI</b><span>Your personal AI companion</span></div></div><div className="portrait-bottom"><div className="wave-mini">{Array.from({length:25},(_,i)=><i key={i} style={{height:`${16+Math.abs(Math.sin(i*.7))*76}%`,animationDelay:`${i*22}ms`}}/>)}</div><span>Natural voice · Real-time response</span></div></div><div className="float-note note-one"><span className="note-icon">✳</span><div><b>Personal memory</b><small>Preferensi kamu, caramu</small></div></div><div className="float-note note-two"><span className="note-icon">◖</span><div><b>Voice ready</b><small>Siap dihubungkan ke TTS</small></div></div></div></section>
 <div className="marquee"><div className="marquee-track">{Array.from({length:2},(_,i)=><div className="marquee-line" key={i}>REAL-TIME CONVERSATION <i/> VOICE READY <i/> PERSONAL MEMORY <i/> MONOCHROME INTERFACE <i/> BUILT WITH CARE <i/></div>)}</div></div>
 <section className="landing-section" id="call"><div className="section-head"><div><div className="kicker">RUANG PANGGILAN</div><h2>Obrolan sederhana.<br/><em>Pengalaman berbeda.</em></h2></div><p className="lede">Masuk ke ruang YUKI untuk mencoba percakapan AI dengan karakter Live2D, respons suara, dan panel chat dalam satu tempat.</p></div><div className="call-preview"><div className="call-preview-art"><div className="call-badge"><i/> YUKI · READY</div><div className="preview-orbit o1"/><div className="preview-orbit o2"/><div className="preview-character">✳</div><div className="preview-bottom"><span>YUKI</span><small>Personal AI assistant</small></div><div className="preview-controls"><span>♩</span><span>◉</span><span>◖</span><span>▤</span><span className="end-call">×</span></div></div><div className="call-preview-copy"><div className="eyebrow light-eyebrow"><i/> READY TO CONNECT</div><h3>Tempat bercerita,<br/><em>bertanya, dan berpikir.</em></h3><p>YUKI bisa membantu brainstorming, menemani belajar, menjelaskan hal baru, atau sekadar mendengarkan ceritamu. Pengalaman suara bergantung pada konfigurasi endpoint yang kamu gunakan.</p><div className="preview-points"><span>✓ Profil personal</span><span>✓ Chat AI terintegrasi</span><span>✓ Model VTuber Live2D</span></div><button className="light-on-dark" onClick={()=>go("chat")}>Masuk ke Live Call <span>↗</span></button></div></div></section>
 <section className="landing-section features-section" id="features"><div className="section-head"><div><div className="kicker">DIBUAT UNTUK KAMU</div><h2>Detail kecil yang<br/><em>membuat perbedaan.</em></h2></div><p className="lede">Antarmuka dirancang agar tidak ramai, tetap ringan, dan membantu kamu fokus pada percakapan.</p></div><div className="feature-grid">{[["◉","Live Call","Ruang chat dan karakter VTuber dalam satu tampilan."],["≋","Voice & TTS","Dukungan endpoint suara yang bisa kamu konfigurasi."],["◇","Personal Memory","Nama, tanggal lahir, topik, dan preferensi personal."],["✳","Custom Prompt","Atur kepribadian dan instruksi AI sesuai kebutuhan."],["⚙","Config JSON","Nama, endpoint, prompt, dan fitur diatur terpusat."],["⌑","Privasi lokal","Profil dan riwayat tersimpan di browser perangkatmu."]].map(([icon,title,desc],i)=><article className="feature-card" key={title} style={{animationDelay:`${i*70}ms`}}><div className="feature-icon">{icon}</div><span className="feature-num">0{i+1}</span><h3>{title}</h3><p>{desc}</p></article>)}</div></section>
 <section className="landing-section how-section" id="how"><div className="how-copy"><div className="kicker">CARA KERJA</div><h2>Tiga langkah menuju<br/><em>obrolan yang hidup.</em></h2><p className="lede">Mulai dari mengenalkan diri hingga menerima respons, semuanya dibuat sesederhana mungkin.</p><button className="dark-btn" onClick={()=>go("onboarding")}>Atur profilku <span>↗</span></button></div><div className="steps">{[["01","Kenalkan dirimu","Atur nama panggilan, tanggal lahir, dan topik favorit."],["02","Masuk ke Live Call","Buka ruang chat dan lihat karakter VTuber YUKI."],["03","Mulai percakapan","Ketik pesan dan dengarkan respons jika TTS tersedia."]].map(([n,t,d])=><div className="step" key={n}><span>{n}</span><div><h3>{t}</h3><p>{d}</p></div></div>)}</div></section>
 <section className="experience-section" id="experience"><div className="kicker">PENGALAMAN PERSONAL</div><blockquote>“Ruang yang tenang untuk bertanya, belajar, dan menata ide — dengan cara yang terasa lebih dekat.”</blockquote><div className="experience-by"><span>✳</span><div><b>YUKI</b><small>Made by Kevsoft Studio</small></div></div><div className="stats-row"><div><strong>01</strong><small>Personal assistant</small></div><div><strong>24/7</strong><small>Siap saat dibutuhkan*</small></div><div><strong>∞</strong><small>Topik percakapan</small></div><div><strong>100%</strong><small>Preferensi bisa diatur</small></div></div><small className="fineprint">*Ketersediaan respons bergantung pada jaringan dan layanan AI yang dikonfigurasi.</small></section>
 <section className="landing-cta"><div className="cta-orbit"/><div className="kicker light-kicker">YOUR SPACE IS READY</div><h2>Mulai percakapan<br/><em>pertamamu.</em></h2><p>Atur ruangmu, kenali YUKI, dan mulai dari hal yang ingin kamu bicarakan hari ini.</p><div className="hero-buttons"><button className="cream-btn" onClick={()=>go("chat")}>Buka Ruang YUKI ↗</button><button className="outline-light" onClick={()=>go("settings")}>Pengaturan</button></div></section><Footer/></div>
}
function Dashboard({ page, profile, onProfile }: {page:string; profile:Profile; onProfile:(p:Profile)=>void}) {
 const [config,setConfig]=useState<any>({}); const [notice,setNotice]=useState("");
 useEffect(()=>{fetch("/config.json").then(r=>r.ok?r.json():{}).then(setConfig).catch(()=>setConfig({}));},[]);
 const savedChats=(()=>{try{return JSON.parse(localStorage.getItem("yuki.chats")||"[]");}catch{return []}})();
 if(page==="home") return <Landing profile={profile}/>;
 if(page==="chat") return <VTuberChat/>;
 return <div className="yuki-app"><aside className="sidebar"><button className="side-brand" onClick={()=>go("home")}><span className="brand-mark">✳</span><span>YUKI<small>PERSONAL AI ASSISTANT</small></span></button><div className="side-label">WORKSPACE</div><nav>{pages.map(([id,label,icon])=><button key={id} className={`nav-item ${page===id?"active":""}`} onClick={()=>go(id)}><span>{icon}</span>{label}</button>)}</nav><div className="sidebar-bottom"><div className="status-dot"/> <span>YUKI ready</span><small>Kevsoft Studio</small></div></aside><main className="dashboard-main"><header className="dash-header"><div className="breadcrumb"><button onClick={()=>go("home")}>YUKI</button> <span>/</span> {pages.find(p=>p[0]===page)?.[1].toUpperCase()}</div><button className="profile-mini" onClick={()=>go("memory")}>{profile.name||"Profil kamu"} ↗</button></header><div className="dash-content">{page==="history"&&<><div className="eyebrow">YOUR ACTIVITY</div><h1>Riwayat percakapan<em>.</em></h1><p className="page-lead">Riwayat yang tersimpan di browser ini.</p>{savedChats.length?savedChats.map((c:any,i:number)=><div className="history-row" key={i}><span>◷</span><div><strong>{c.title||"Percakapan dengan YUKI"}</strong><small>{c.date||"Tersimpan lokal"}</small></div><button onClick={()=>go("chat")}>Buka ↗</button></div>):<div className="empty-state"><span>◷</span><strong>Belum ada riwayat</strong><p>Mulai percakapan untuk membuat riwayat pertamamu.</p><button className="primary-btn" onClick={()=>go("chat")}>Mulai chat ↗</button></div>}</>}
 {page==="memory"&&<><div className="eyebrow">PERSONALIZATION</div><h1>Profil & preferensi<em>.</em></h1><p className="page-lead">Informasi ini membantu YUKI memberi jawaban lebih relevan. Tersimpan di perangkatmu.</p><section className="settings-card"><label className="field-label">Nama panggilan</label><input className="yuki-input" value={profile.name} maxLength={40} onChange={e=>onProfile({...profile,name:e.target.value})}/><label className="field-label">Tanggal lahir</label><input className="yuki-input" type="date" max={new Date().toISOString().slice(0,10)} value={profile.birthday} onChange={e=>onProfile({...profile,birthday:e.target.value})}/><label className="field-label">Topik favorit</label><div className="topic-grid">{topics.map(t=><button key={t} className={`topic-chip ${profile.topics.includes(t)?"selected":""}`} onClick={()=>onProfile({...profile,topics:profile.topics.includes(t)?profile.topics.filter(x=>x!==t):[...profile.topics,t]})}>{profile.topics.includes(t)?"✓":"＋"} {t}</button>)}</div><label className="field-label">Tentang kamu</label><textarea className="yuki-input" rows={4} value={profile.about} placeholder="Preferensi atau konteks yang ingin YUKI ketahui..." onChange={e=>onProfile({...profile,about:e.target.value})}/><button className="primary-btn" onClick={()=>{localStorage.setItem("yuki.profile",JSON.stringify(profile));setNotice("Profil tersimpan di perangkat ini.");}}>Simpan profil ↗</button>{notice&&<p className="success-note">✓ {notice}</p>}</section></>}
 {page==="settings"&&<><div className="eyebrow">PREFERENCES & CONFIGURATION</div><h1>Pengaturan<em>.</em></h1><p className="page-lead">Konfigurasi dasar dibaca dari <code>public/config.json</code>. Jangan simpan API key rahasia di file publik.</p><section className="settings-card"><h2>Application config</h2><div className="config-line"><span>AI name</span><strong>{config.aiName||"YUKI"}</strong></div><div className="config-line"><span>Text API endpoint</span><code>{config.api?.text||"/api/chat"}</code></div><div className="config-line"><span>Voice API endpoint</span><code>{config.api?.voice||"/api/tts"}</code></div><div className="config-line"><span>Prompt</span><p>{config.prompt||"Default prompt"}</p></div><div className="config-line"><span>Local profile</span><strong>{profile.name||"Belum diatur"}</strong></div><button className="ghost-btn" onClick={()=>{localStorage.removeItem("yuki.chats");setNotice("Riwayat lokal dihapus.");}}>Hapus riwayat lokal</button>{notice&&<p className="success-note">✓ {notice}</p>}<p className="privacy-note">Profil dan riwayat berada di browser lokal. Konteks yang dibutuhkan percakapan dapat dikirim ke endpoint AI.</p></section></>}
 {page==="about"&&<><div className="eyebrow">MEET YOUR ASSISTANT</div><h1>Thoughtful by design<em>.</em></h1><p className="page-lead">YUKI adalah personal assistant yang dibuat oleh Kevsoft Studio, dirancang untuk terasa ringan, tenang, dan mudah digunakan.</p><section className="about-card"><div className="about-logo">✳</div><div><h2>YUKI</h2><p>Personal AI assistant · Made by Kevsoft Studio</p><span className="online-tag"><i/> BUILT FOR EVERYDAY IDEAS</span></div></section><section className="settings-card"><h2>Powered by Kevsoft Studio</h2><a className="link-row" href="https://github.com/kevsoftstudio" target="_blank" rel="noreferrer">GitHub <span>github.com/kevsoftstudio ↗</span></a><a className="link-row" href="mailto:kevsoftstudio@gmail.com">Email <span>kevsoftstudio@gmail.com ↗</span></a><a className="link-row" href="https://dev.to/kevsoftstudio" target="_blank" rel="noreferrer">Dev.to <span>dev.to/kevsoftstudio ↗</span></a><a className="link-row" href="https://t.me/kevsoftstudio" target="_blank" rel="noreferrer">Telegram <span>t.me/kevsoftstudio ↗</span></a></section></>}
 </div><Footer/></main></div>
}
export default function App(){const [path,setPath]=useState(location.pathname.replace(/^\/+|\/+$/g,"")||"home");const [profile,setProfile]=useState<Profile>(readProfile());const [ready,setReady]=useState(()=>localStorage.getItem("yuki.onboarded")==="true");useEffect(()=>{const pop=()=>setPath(location.pathname.replace(/^\/+|\/+$/g,"")||"home");window.addEventListener("popstate",pop);return()=>window.removeEventListener("popstate",pop);},[]);useEffect(()=>{try{localStorage.setItem("yuki.profile",JSON.stringify(profile));}catch{}},[profile]);const finish=(p:Profile)=>{setProfile(p);localStorage.setItem("yuki.profile",JSON.stringify(p));localStorage.setItem("yuki.onboarded","true");setReady(true);go("home");};if(!ready&&path!=="onboarding")return <Onboarding onDone={finish}/>;if(path==="onboarding")return <Onboarding onDone={finish}/>;return <Dashboard page={pages.some(p=>p[0]===path)?path:"home"} profile={profile} onProfile={setProfile}/>;}
