// ─────────────────────────────────────────────────────────────────────────────
// Pustaka gerakan. Pose kontak (tangan ke pipi/dagu/dada/pinggang/dll) dihitung
// dengan pencarian numerik pada skeleton model (bukan ditebak) lalu dibekukan di sini.
// Semua preset ditulis untuk tangan KANAN; sisi kiri otomatis lewat mirror.
// ─────────────────────────────────────────────────────────────────────────────
import type { MotionDef, Key } from "./engine";
import type { Pose } from "./channels";

type Shape = { Idx: number; Mid: number; Rng: number; Thumb: number; Spread: number };
export const HAND: Record<string, Shape> = {
  open: { Idx: 0, Mid: 0, Rng: 0, Thumb: 0.05, Spread: 0.55 },
  flat: { Idx: 0, Mid: 0, Rng: 0, Thumb: 0.15, Spread: 0 },
  relax: { Idx: 0.14, Mid: 0.18, Rng: 0.24, Thumb: 0.18, Spread: 0.1 },
  soft: { Idx: 0.3, Mid: 0.34, Rng: 0.4, Thumb: 0.25, Spread: 0.05 },
  fist: { Idx: 1, Mid: 1, Rng: 1, Thumb: 0.8, Spread: 0 },
  point: { Idx: 0, Mid: 1, Rng: 1, Thumb: 0.7, Spread: 0 },
  peace: { Idx: 0, Mid: 0, Rng: 1, Thumb: 0.8, Spread: 1 },
  thumbsUp: { Idx: 1, Mid: 1, Rng: 1, Thumb: 0, Spread: 0 },
  ok: { Idx: 0.8, Mid: 0, Rng: 0, Thumb: 0.75, Spread: 0.5 },
  heart: { Idx: 0.55, Mid: 0.75, Rng: 0.85, Thumb: 0.2, Spread: 0 },
  claw: { Idx: 0.5, Mid: 0.5, Rng: 0.5, Thumb: 0.4, Spread: 0.7 },
};
const hand = (s: "l" | "r", shape: keyof typeof HAND): Pose => {
  const h = HAND[shape];
  return { [s + "Idx"]: h.Idx, [s + "Mid"]: h.Mid, [s + "Rng"]: h.Rng, [s + "Thumb"]: h.Thumb, [s + "Spread"]: h.Spread };
};
const arm = (s: "l" | "r", raise: number, az: number, elbow: number, plane = 0, roll = 0, wrist = 0): Pose => ({
  [s + "Raise"]: raise,
  [s + "Az"]: az,
  [s + "Elbow"]: elbow,
  [s + "Plane"]: plane,
  [s + "Roll"]: roll,
  [s + "Wrist"]: wrist,
});
export const A = {
  R: (raise: number, az: number, elbow: number, plane = 0, roll = 0, wrist = 0) => arm("r", raise, az, elbow, plane, roll, wrist),
  L: (raise: number, az: number, elbow: number, plane = 0, roll = 0, wrist = 0) => arm("l", raise, az, elbow, plane, roll, wrist),
};
export const HR = (n: keyof typeof HAND) => hand("r", n);
export const HL = (n: keyof typeof HAND) => hand("l", n);
const both = (raise: number, az: number, elbow: number, plane: number, shape: keyof typeof HAND, roll = 0, wrist = 0): Pose => ({
  ...A.R(raise, az, elbow, plane, roll, wrist),
  ...A.L(raise, az, elbow, plane, roll, wrist),
  ...HR(shape),
  ...HL(shape),
});
const P = (...p: Pose[]): Pose => Object.assign({}, ...p);
const K = (t: number, ...p: Pose[]): Key => ({ t, pose: P(...p) });

// Pose kontak hasil pencarian numerik (lihat tests/ik)
const POSE = {
  chin: A.R(62, 51, 139, -18),
  mouth: A.R(69, 65, 133, -16),
  cheek: (s: "l" | "r") => arm(s, 62, 59, 143, 8),
  temple: A.R(90, 60, 120, 17),
  headTop: A.R(109, 58, 110, 27),
  eyes: (s: "l" | "r") => arm(s, 79, 59, 128, -3),
  chest: A.R(73, 54, 125, -79),
  hip: (s: "l" | "r") => arm(s, 66, -6, 100, -69),
  crossTop: A.R(65, 103, 90, -96),
  crossLow: A.L(47, 104, 84, -100),
  hug: (s: "l" | "r") => arm(s, 56, 104, 103, -92),
  behind: (s: "l" | "r") => arm(s, 60, -40, 103, -77),
  clasp: (s: "l" | "r") => arm(s, 53, 35, 93, -81),
  pray: (s: "l" | "r") => arm(s, 41, 18, 115, -39),
  clap: (s: "l" | "r") => arm(s, 35, 58, 97, -27),
  heart: (s: "l" | "r") => arm(s, 113, 62, 93, 10),
  ear: A.R(80, 67, 141, 17),
  hairFlip: A.R(104, 71, 131, 33),
  backHead: A.R(126, 64, 114, 29),
  forehead: A.R(94, 65, 116, -3),
  support: A.L(33, 104, 78, -78),
  fwd: A.R(88, 92, 8, 0),
};
const bothOf = (f: (s: "l" | "r") => Pose, shape: keyof typeof HAND): Pose => P(f("l"), f("r"), HL(shape), HR(shape));

export const MOTIONS: MotionDef[] = [
  // ───────── sapaan & sosial ─────────
  {
    name: "melambai",
    aliases: ["melambai", "lambai", "melambaikan tangan", "lambaikan tangan", "lambaian", "wave", "waving", "say hi", "menyapa dengan tangan", "salam tangan", "halo", "hai", "dadah", "bye bye"],
    dur: 2.7,
    holdAt: 0,
    keys: [K(0, A.R(112, 35, 100, 75), HR("open"), { headR: 4, fHappy: 0.55, torsoR: -2 })],
    osc: [
      { ch: "rPlane", amp: 24, hz: 2.3, from: 0.35 },
      { ch: "rWrist", amp: 10, hz: 2.3, phase: 0.25, from: 0.35 },
      { ch: "headR", amp: 2, hz: 1.15, from: 0.3 },
    ],
    moods: ["Senang", "Malu"],
  },
  {
    name: "melambai dua tangan",
    aliases: ["melambai dua tangan", "lambai dua tangan", "lambaikan kedua tangan", "wave both", "melambai heboh", "dadah dadah"],
    dur: 2.8,
    holdAt: 0,
    keys: [K(0, A.R(115, 35, 100, 75), A.L(115, 35, 100, 75), HR("open"), HL("open"), { headR: 5, fHappy: 0.9 })],
    osc: [
      { ch: "rPlane", amp: 24, hz: 2.4, from: 0.35 },
      { ch: "lPlane", amp: 24, hz: 2.4, phase: 0.5, from: 0.35 },
      { ch: "hipsR", amp: 2, hz: 1.2, from: 0.3 },
    ],
  },
  {
    name: "membungkuk",
    aliases: ["membungkuk", "bungkuk", "hormat", "memberi hormat", "salam hormat", "bow", "bowing", "menunduk hormat", "ojigi", "salam"],
    dur: 2.5,
    holdAt: 2,
    keys: [
      K(0, { torsoP: -2, headP: -2 }),
      K(0.55, { torsoP: 28, headP: 8, hipsP: 8 }, both(22, 70, 35, -30, "relax")),
      K(1.2, { torsoP: 30, headP: 9, hipsP: 9 }, both(22, 70, 35, -30, "relax")),
      K(1.9, { torsoP: 0, headP: 0, hipsP: 0 }),
    ],
    shot: "mid",
  },
  {
    name: "mengangguk",
    aliases: ["mengangguk", "angguk", "anggukan", "mengangguk setuju", "nod", "nodding", "setuju", "betul", "oke setuju"],
    dur: 1.2,
    light: true,
    beat: true,
    keys: [K(0, { headP: 0 }), K(0.2, { headP: 11, torsoP: 2 }), K(0.45, { headP: -1 }), K(0.68, { headP: 9, torsoP: 1.5 }), K(1, { headP: 0, torsoP: 0 })],
    inT: 0.12,
    outT: 0.2,
  },
  {
    name: "menggeleng",
    aliases: ["menggeleng", "geleng", "menggelengkan kepala", "gelengan", "shake head", "tidak", "enggak", "nggak", "gak", "no", "menolak", "tak setuju"],
    dur: 1.6,
    light: true,
    keys: [K(0, { fSad: 0.15 })],
    osc: [
      { ch: "headY", amp: 15, hz: 2.4, from: 0, to: 1.4 },
      { ch: "torsoY", amp: 3, hz: 2.4, from: 0, to: 1.4 },
    ],
    inT: 0.1,
    outT: 0.3,
  },
  {
    name: "mengangkat bahu",
    aliases: ["mengangkat bahu", "angkat bahu", "mengangkat kedua bahu", "shrug", "entahlah", "tidak tahu", "gak tahu", "nggak tahu", "mana aku tahu", "terserah", "acuh"],
    dur: 2.1,
    holdAt: 0,
    keys: [K(0, { lShrug: 16, rShrug: 16, headR: 7, headP: -2, fRelax: 0.3 }, both(26, 30, 42, 50, "open", 0, 8))],
  },
  {
    name: "hormat militer",
    aliases: ["hormat militer", "memberi hormat dengan tangan", "salute", "siap", "siap bos", "siap komandan", "hormat bendera"],
    dur: 2.2,
    holdAt: 0,
    keys: [K(0, POSE.temple, HR("flat"), { headP: -2, torsoP: -2, fHappy: 0.35 })],
  },
  {
    name: "peace",
    aliases: ["peace", "tanda peace", "tanda v", "v sign", "victory", "dua jari", "salam damai", "piss", "peace sign"],
    dur: 2.3,
    holdAt: 0,
    keys: [K(0, A.R(100, 58, 112, 70), HR("peace"), { headR: 9, fHappy: 0.85 })],
  },
  {
    name: "jempol",
    aliases: ["jempol", "mengacungkan jempol", "acungkan jempol", "thumbs up", "thumb up", ],
    dur: 2.2,
    holdAt: 0,
    keys: [K(0, A.R(62, 72, 100, 35, 0, -5), HR("thumbsUp"), { headP: 2, fHappy: 0.75 })],
  },
  {
    name: "tanda oke",
    aliases: ["tanda oke", "tanda ok", "ok sign", "okay sign", "oke", "ok", "okay", "siap laksanakan"],
    dur: 2.1,
    holdAt: 0,
    keys: [K(0, A.R(68, 70, 105, 30), HR("ok"), { headR: 5, fHappy: 0.6 })],
  },
  {
    name: "menunjuk",
    aliases: ["menunjuk", "tunjuk", "menunjuk ke depan", "menunjuk kamu", "menunjuk ke arah kamu", "point", "pointing", "itu dia", "lihat itu", "menunjuk ke sana"],
    dur: 2,
    holdAt: 0,
    keys: [K(0, POSE.fwd, HR("point"), { headP: -1 })],
  },
  {
    name: "menunjuk atas",
    aliases: ["menunjuk atas", "menunjuk ke atas", "tunjuk atas", "point up", "ke atas", "lihat ke atas"],
    dur: 2,
    holdAt: 0,
    keys: [K(0, A.R(168, 40, 8, 0), HR("point"), { headP: -10, gazeY: 10, torsoP: -3 })],
  },
  {
    name: "menunjuk diri sendiri",
    aliases: ["menunjuk diri sendiri", "tunjuk diri sendiri", "menunjuk dirinya", "point self", "menunjuk dada sendiri"],
    dur: 2,
    holdAt: 0,
    keys: [K(0, A.R(73, 54, 125, -79), HR("point"), { headP: 3, fHappy: 0.5 })],
  },
  {
    name: "memanggil",
    aliases: ["memanggil", "panggil", "melambai memanggil", "isyarat sini", "beckon", "come here", "sini", "ayo sini", "mendekat", "kemari", "mari sini"],
    dur: 2.5,
    holdAt: 0,
    keys: [K(0, A.R(46, 66, 63, -9, -70), HR("open"), { headR: 5, fHappy: 0.55 })],
    osc: [
      { ch: "rWrist", amp: 22, hz: 2.0, from: 0.4 },
      { ch: "rIdx", amp: 0.3, hz: 2.0, offset: 0.35, from: 0.4 },
      { ch: "rMid", amp: 0.3, hz: 2.0, offset: 0.35, phase: 0.1, from: 0.4 },
    ],
  },
  {
    name: "jari no",
    aliases: ["jari no", "menggoyang jari", "goyang jari", "jangan", "tidak boleh", "no no", "tsk tsk", "menggelengkan jari", "dilarang"],
    dur: 2.1,
    holdAt: 0,
    keys: [K(0, A.R(75, 70, 95, 75), HR("point"), { headR: 3, fAngry: 0.1 })],
    osc: [{ ch: "rPlane", amp: 18, hz: 2.6, from: 0.4 }],
  },
  {
    name: "ide",
    aliases: ["ide", "aha", "eureka", "dapat ide", "mengacungkan jari", "acungkan jari", "ding", "oh iya", "ingat sesuatu", "teringat"],
    dur: 2,
    holdAt: 0,
    keys: [K(0, A.R(125, 50, 75, 70), HR("point"), { headP: -4, fSurp: 0.35, fHappy: 0.6 })],
  },
  // ───────── ekspresi tubuh ─────────
  {
    name: "membuka tangan",
    aliases: ["membuka tangan", "buka tangan", "merentangkan tangan", "rentangkan tangan", "menyambut", "sambut", "welcome", "selamat datang", "ta da", "tada", "open arms", "membuka lengan"],
    dur: 2.6,
    holdAt: 0,
    keys: [K(0, both(82, 12, 28, 25, "open"), { torsoP: -5, headP: -4, fHappy: 0.85 })],
    shot: "mid",
  },
  {
    name: "memeluk diri",
    aliases: ["memeluk diri", "peluk diri", "memeluk badan", "peluk badan", "kedinginan", "dingin", "hug self", "memeluk tubuh sendiri", "merinding", "takut"],
    dur: 3.2,
    holdAt: 0,
    keys: [K(0, bothOf(POSE.hug, "soft"), { torsoP: 6, headP: 6, lShrug: 4, rShrug: 4, fRelax: 0.5, fSad: 0.15 })],
    moods: ["Sedih", "Malu"],
  },
  {
    name: "menyilangkan tangan",
    aliases: ["menyilangkan tangan", "silang tangan", "melipat tangan", "lipat tangan", "tangan bersilang", "cross arms", "arms crossed", "ngambek", "merajuk", "sok cuek", "bersedekap"],
    dur: 3.4,
    holdAt: 0,
    keys: [K(0, POSE.crossTop, POSE.crossLow, HR("soft"), HL("soft"), { torsoP: -3, headY: 12, headP: -2, fAngry: 0.28, shift: -0.5 })],
    moods: ["Tsundere", "Marah"],
  },
  {
    name: "tangan di pinggang",
    aliases: ["tangan di pinggang", "berkacak pinggang", "kacak pinggang", "hands on hips", "pose pinggang", "percaya diri", "bangga", "sombong"],
    dur: 3.2,
    holdAt: 0,
    keys: [K(0, bothOf(POSE.hip, "relax"), { torsoP: -3, headP: -3, fHappy: 0.45, shift: 0.6 })],
    moods: ["Senang", "Tsundere"],
  },
  {
    name: "berpikir",
    aliases: ["berpikir", "pikir", "mikir", "memikirkan", "sedang berpikir", "memegang dagu", "pegang dagu", "tangan di dagu", "think", "thinking", "hmm", "menimbang", "merenung"],
    dur: 3.6,
    holdAt: 0,
    keys: [K(0, POSE.chin, POSE.support, HR("soft"), HL("relax"), { headR: 7, headP: 5, gazeY: 8, gazeX: 12, fRelax: 0.3 })],
    moods: ["Bingung", "Serius"],
  },
  {
    name: "menggaruk kepala",
    aliases: ["menggaruk kepala", "garuk kepala", "garuk garuk kepala", "scratch head", "bingung garuk", "salah tingkah garuk", "kepala gatal"],
    dur: 2.8,
    holdAt: 0,
    keys: [K(0, POSE.headTop, HR("claw"), { headR: 6, fHappy: 0.3, fSad: 0.15 })],
    osc: [
      { ch: "rPlane", amp: 9, hz: 4.2, from: 0.4 },
      { ch: "rWrist", amp: 8, hz: 4.2, phase: 0.25, from: 0.4 },
    ],
    moods: ["Bingung", "Malu"],
    idle: 0.4,
  },
  {
    name: "menggaruk pipi",
    aliases: ["menggaruk pipi", "garuk pipi", "scratch cheek", "pipi gatal"],
    dur: 2.4,
    holdAt: 0,
    keys: [K(0, POSE.cheek("r"), HR("point"), { headR: 5, headP: 3, fHappy: 0.4, fRelax: 0.3 })],
    osc: [{ ch: "rWrist", amp: 10, hz: 3.4, from: 0.4 }],
    idle: 0.5,
    moods: ["Malu", "Bingung"],
  },
  {
    name: "menutup wajah",
    aliases: ["menutup wajah", "tutup wajah", "tutup muka", "menutupi wajah", "menutup mata", "tutup mata", "sembunyi", "bersembunyi", "cover face", "hide face", "malu banget", "malu malu"],
    dur: 3,
    holdAt: 0,
    keys: [K(0, bothOf(POSE.eyes, "flat"), { headP: 8, torsoP: 4, fHappy: 0.3, fBlinkL: 0.5, fBlinkR: 0.5 })],
    moods: ["Malu"],
  },
  {
    name: "tangan di pipi",
    aliases: ["tangan di pipi", "memegang pipi", "pegang pipi", "menangkup pipi", "pipi merona", "cheeks", "hands on cheeks", "tersipu malu", "gemas"],
    dur: 3,
    holdAt: 0,
    keys: [K(0, bothOf(POSE.cheek, "flat"), { headR: 6, headP: 3, fHappy: 0.7, fRelax: 0.3 })],
    moods: ["Malu", "Senang"],
  },
  {
    name: "memegang dada",
    aliases: ["memegang dada", "pegang dada", "tangan di dada", "menaruh tangan di dada", "hand on chest", "terharu", "lega", "tersentuh", "syukurlah", "hati hangat"],
    dur: 3,
    holdAt: 0,
    keys: [K(0, POSE.chest, HR("flat"), { headP: 5, torsoP: 2, fRelax: 0.5, fHappy: 0.3 })],
    moods: ["Senang", "Sedih"],
  },
  {
    name: "tepuk tangan",
    aliases: ["tepuk tangan", "bertepuk tangan", "menepuk tangan", "clap", "clapping", "applause", "memberi applaus", "wow tepuk"],
    dur: 2.5,
    holdAt: 0,
    keys: [K(0, bothOf(POSE.clap, "flat"), { fHappy: 0.85, headP: -2, torsoP: -2 })],
    osc: [
      { ch: "rPlane", amp: 20, offset: 20, hz: 2.9, from: 0.3 },
      { ch: "lPlane", amp: 20, offset: 20, hz: 2.9, from: 0.3 },
    ],
  },
  {
    name: "semangat",
    aliases: ["semangat", "mengepalkan tangan", "kepalkan tangan", "fist pump", "fighting", "ganbatte", "yosh", "ayo semangat", "optimis", "pasti bisa", "bangkit"],
    dur: 2.4,
    holdAt: 1,
    keys: [K(0, A.R(30, 60, 100, 40), HR("fist")), K(0.28, A.R(122, 35, 95, 60), HR("fist"), { fHappy: 1, torsoP: -4, headP: -4 })],
    osc: [
      { ch: "rElbow", amp: 14, hz: 2.2, from: 0.55 },
      { ch: "hipsDY", amp: 1.2, hz: 2.2, from: 0.55 },
    ],
  },
  {
    name: "bersorak",
    aliases: ["bersorak", "sorak", "hore", "horee", "yey", "yeay", "yeyy", "menang", "yes yes", "cheer", "celebrate", "merayakan", "kemenangan"],
    dur: 2.6,
    holdAt: 0,
    keys: [K(0, both(160, 25, 12, 0, "open"), { fHappy: 1, torsoP: -6, headP: -6 })],
    osc: [
      { ch: "hipsDY", amp: 2, hz: 2.6, from: 0.3 },
      { ch: "crouch", amp: 0.08, hz: 2.6, from: 0.3, offset: 0.08 },
    ],
    shot: "mid",
  },
  {
    name: "menari",
    aliases: ["menari", "tari", "joget", "berjoget", "goyang", "bergoyang", "dance", "dancing", "menari kecil", "bergoyang goyang", "ikut irama"],
    dur: 4.6,
    holdAt: 0,
    keys: [K(0, both(70, 30, 50, 20, "open"), { fHappy: 1 })],
    osc: [
      { ch: "hipsR", amp: 5, hz: 0.9, from: 0.4 },
      { ch: "hipsX", amp: 3, hz: 0.9, phase: 0.25, from: 0.4 },
      { ch: "torsoR", amp: -3, hz: 0.9, from: 0.4 },
      { ch: "torsoY", amp: 8, hz: 0.45, from: 0.4 },
      { ch: "headR", amp: 5, hz: 0.9, phase: 0.5, from: 0.4 },
      { ch: "crouch", amp: 0.1, offset: 0.12, hz: 1.8, from: 0.4 },
      { ch: "rRaise", amp: 22, hz: 0.9, from: 0.4 },
      { ch: "lRaise", amp: 22, hz: 0.9, phase: 0.5, from: 0.4 },
      { ch: "rElbow", amp: 14, hz: 1.8, from: 0.4 },
      { ch: "lElbow", amp: 14, hz: 1.8, phase: 0.5, from: 0.4 },
    ],
    shot: "full",
  },
  {
    name: "berputar",
    aliases: ["berputar", "putar", "muter", "memutar badan", "putar badan", "spin", "twirl", "berputar putar", "pirouette", "memutar"],
    dur: 2.1,
    inT: 0.1,
    outT: 0.3,
    keys: [
      K(0, { turn: 0 }, both(14, 6, 14, 0, "relax")),
      K(0.15, both(70, 15, 25, 0, "open"), { crouch: 0.12 }),
      K(1.6, { turn: 360 }, both(70, 15, 25, 0, "open"), { crouch: 0.02, hipsDY: 2 }),
      K(2.1, { turn: 360 }, both(18, 8, 16, 0, "relax"), { crouch: 0 }),
    ],
    shot: "full",
  },
  {
    name: "melompat",
    aliases: ["melompat", "lompat", "loncat", "meloncat", "jump", "jumping", "hop", "melonjak", "lompat kegirangan", "loncat loncat"],
    dur: 1.9,
    inT: 0.08,
    outT: 0.35,
    keys: [
      K(0, { crouch: 0, hipsDY: 0 }),
      K(0.3, { crouch: 0.75, torsoP: 12 }, both(8, -35, 25, 0, "relax")),
      K(0.44, { crouch: 0.05, hipsDY: 0, torsoP: -4 }),
      K(0.64, { hipsDY: 28, crouch: 0.05 }, both(120, 35, 20, 0, "open"), { fHappy: 1 }),
      K(0.86, { hipsDY: 0, crouch: 0.05 }, both(75, 20, 25, 0, "open")),
      K(1.05, { crouch: 0.55, torsoP: 6, hipsDY: 0 }, both(30, 10, 30, 0, "relax")),
      K(1.5, { crouch: 0, torsoP: 0 }),
    ],
    shot: "full",
  },
  {
    name: "tertawa",
    aliases: ["tertawa", "tawa", "ngakak", "tertawa terbahak", "terkekeh", "kekeh", "haha", "hahaha", "wkwk", "lol", "laugh", "laughing", "geli", "lucu"],
    dur: 2.5,
    holdAt: 0,
    keys: [K(0, { fHappy: 1, headP: -4, torsoP: -3, fMouthA: 0.5 })],
    osc: [
      { ch: "torsoP", amp: 2.8, hz: 5.2, from: 0.2 },
      { ch: "lShrug", amp: 3.5, hz: 5.2, from: 0.2 },
      { ch: "rShrug", amp: 3.5, hz: 5.2, from: 0.2 },
      { ch: "headP", amp: 2.5, hz: 5.2, phase: 0.1, from: 0.2 },
      { ch: "fMouthA", amp: 0.22, hz: 5.2, from: 0.2 },
      { ch: "hipsDY", amp: 0.5, hz: 5.2, from: 0.2 },
    ],
    moods: ["Senang"],
    idle: 0.15,
  },
  {
    name: "menguap",
    aliases: ["menguap", "uap", "yawn", "yawning", "ngantuk", "mengantuk", "capek ngantuk", "kantuk"],
    dur: 3.4,
    holdAt: 0,
    keys: [K(0, POSE.mouth, HR("open"), { headP: -6, torsoP: -3, fMouthA: 1, fBlinkL: 0.75, fBlinkR: 0.75, fRelax: 0.5 })],
    idle: 0.12,
  },
  {
    name: "menangis",
    aliases: ["menangis", "nangis", "mengusap mata", "usap mata", "mengelap air mata", "menyeka air mata", "cry", "crying", "air mata", "sedih banget", "terisak"],
    dur: 3.2,
    holdAt: 0,
    keys: [K(0, bothOf(POSE.eyes, "relax"), { headP: 10, torsoP: 4, fSad: 1, fBlinkL: 0.6, fBlinkR: 0.6 })],
    osc: [
      { ch: "rPlane", amp: 6, hz: 3, from: 0.5 },
      { ch: "lPlane", amp: 6, hz: 3, phase: 0.5, from: 0.5 },
      { ch: "lShrug", amp: 1.5, hz: 2.5, from: 0.5 },
      { ch: "rShrug", amp: 1.5, hz: 2.5, phase: 0.3, from: 0.5 },
    ],
    moods: ["Sedih"],
  },
  {
    name: "terkejut",
    aliases: ["terkejut", "kaget", "tersentak", "kejut", "startle", "surprised", "terperanjat", "mundur kaget", "astaga", "ya ampun", "waduh", "hah"],
    dur: 2.2,
    holdAt: 1,
    inT: 0.1,
    keys: [
      K(0, { fSurp: 0 }),
      K(0.14, { torsoP: -10, headP: -8, hipsZ: -5, lShrug: 10, rShrug: 10, fSurp: 1 }, both(55, 60, 100, -30, "open")),
      K(0.9, { torsoP: -8, headP: -6, hipsZ: -4, fSurp: 0.8 }, both(55, 60, 100, -30, "open")),
      K(1.9, { torsoP: -2, headP: -1, hipsZ: 0, fSurp: 0.2 }),
    ],
    moods: ["Kaget"],
  },
  {
    name: "menghela napas",
    aliases: ["menghela napas", "hela napas", "menarik napas", "tarik napas", "sigh", "desah", "mendesah", "huft", "haah", "napas panjang", "lelah", "capek"],
    dur: 3,
    keys: [
      K(0, { lShrug: 12, rShrug: 12, torsoP: -4, headP: -2 }),
      K(0.9, { lShrug: 14, rShrug: 14, torsoP: -5, headP: -3 }),
      K(1.7, { lShrug: -2, rShrug: -2, torsoP: 7, headP: 8, fRelax: 0.6 }),
      K(2.6, { lShrug: 0, rShrug: 0, torsoP: 3, headP: 4 }),
    ],
    idle: 0.7,
    light: true,
  },
  {
    name: "merenggangkan badan",
    aliases: ["merenggangkan badan", "regangkan badan", "meregangkan badan", "meregang", "stretch", "stretching", "peregangan", "menggeliat", "geliat", "melemaskan badan"],
    dur: 3.8,
    holdAt: 1,
    keys: [
      K(0, { torsoP: 0 }),
      K(1, both(172, 70, 6, 0, "flat"), { torsoP: -12, headP: -8, hipsP: -4, fRelax: 0.4 }),
      K(2.9, both(172, 70, 6, 0, "flat"), { torsoP: -12, headP: -8, hipsP: -4 }),
      K(3.6, both(14, 6, 14, 0, "relax"), { torsoP: 0, headP: 0, hipsP: 0 }),
    ],
    idle: 0.2,
    shot: "mid",
  },
  // ───────── kepala, mata, wajah ─────────
  {
    name: "memiringkan kepala",
    aliases: ["memiringkan kepala", "miringkan kepala", "kepala miring", "tilt head", "head tilt", "penasaran", "heran", "imut", "manis", "lucu imut"],
    dur: 2.4,
    holdAt: 0,
    light: true,
    idle: 1,
    keys: [K(0, { headR: 12, headP: 3, fHappy: 0.3 })],
  },
  {
    name: "menunduk",
    aliases: ["menunduk", "tunduk", "melihat ke bawah", "lihat bawah", "look down", "murung", "kepala tertunduk", "malu menunduk"],
    dur: 2.6,
    holdAt: 0,
    light: true,
    keys: [K(0, { headP: 15, torsoP: 5, gazeY: -12 })],
  },
  {
    name: "membuang muka",
    aliases: ["membuang muka", "buang muka", "memalingkan wajah", "palingkan wajah", "menoleh ke samping", "menoleh", "look away", "hmph", "cuek", "mengalihkan pandangan", "pura pura tidak peduli", "tsun"],
    dur: 2.8,
    holdAt: 0,
    light: true,
    keys: [K(0, { headY: 24, gazeX: 22, headP: 2, torsoY: 6, fAngry: 0.12, fHappy: 0.1 })],
    moods: ["Tsundere"],
  },
  {
    name: "melihat sekeliling",
    aliases: ["melihat sekeliling", "lihat sekeliling", "celingak celinguk", "menengok kiri kanan", "look around", "mencari cari", "mencari sesuatu", "mengamati"],
    dur: 3.4,
    light: true,
    idle: 1,
    keys: [
      K(0, { headY: 0 }),
      K(0.5, { headY: 24, gazeX: 20, torsoY: 4 }),
      K(1.3, { headY: 24, gazeX: 20, torsoY: 4 }),
      K(1.9, { headY: -22, gazeX: -20, torsoY: -4 }),
      K(2.7, { headY: -22, gazeX: -20, torsoY: -4 }),
      K(3.3, { headY: 0, gazeX: 0, torsoY: 0 }),
    ],
  },
  {
    name: "mengedip",
    aliases: ["mengedip", "kedip", "mengedipkan mata", "kedipkan mata", "wink", "winking", "kedip mata", "genit", "menggoda"],
    dur: 1.1,
    light: true,
    inT: 0.08,
    outT: 0.25,
    keys: [K(0, { fBlinkR: 0 }), K(0.12, { fBlinkR: 1, fHappy: 0.6, headR: 6 }), K(0.5, { fBlinkR: 1, fHappy: 0.6, headR: 6 }), K(0.7, { fBlinkR: 0, fHappy: 0.5, headR: 4 })],
  },
  {
    name: "tersenyum",
    aliases: ["tersenyum", "senyum", "senyum manis", "smile", "smiling", "tersenyum manis", "senyum tipis", "senyum lebar", "berseri"],
    dur: 2.8,
    holdAt: 0,
    light: true,
    idle: 0.6,
    keys: [K(0, { fHappy: 0.8, fRelax: 0.2 })],
  },
  {
    name: "cemberut",
    aliases: ["cemberut", "merengut", "manyun", "pout", "kesal manja", "ngambek manja", "bete", "sebal", "mengerucutkan bibir"],
    dur: 2.8,
    holdAt: 0,
    light: true,
    keys: [K(0, { fSad: 0.45, fAngry: 0.3, headP: 5, torsoP: 2, fMouthO: 0.35 })],
    moods: ["Tsundere"],
  },
  {
    name: "tersipu",
    aliases: ["tersipu", "tersipu sipu", "merona", "blush", "blushing", "salah tingkah", "grogi", "gugup", "deg degan", "berdebar"],
    dur: 3,
    holdAt: 0,
    keys: [K(0, bothOf(POSE.clasp, "soft"), { fHappy: 0.35, fRelax: 0.5, headP: 9, headR: 6, gazeY: -10, gazeX: 10, lShrug: 5, rShrug: 5 })],
    moods: ["Malu"],
  },
  {
    name: "marah",
    aliases: ["marah", "murka", "geram", "kesal", "angry", "mengepalkan kedua tangan", "emosi", "naik darah", "jengkel", "gusar"],
    dur: 2.8,
    holdAt: 0,
    keys: [K(0, both(25, 35, 85, -20, "fist"), { fAngry: 1, torsoP: 5, headP: 6, lShrug: 4, rShrug: 4 })],
    osc: [{ ch: "torsoY", amp: 0.8, hz: 7, from: 0.3 }, { ch: "headR", amp: 0.8, hz: 6, from: 0.3 }],
    moods: ["Marah"],
  },
  // ───────── lain-lain ─────────
  {
    name: "mengirim cium",
    aliases: ["mengirim cium", "kirim cium", "cium jauh", "blow kiss", "flying kiss", "kiss", "muah", "mwah", "ciuman jauh"],
    dur: 2.8,
    holdAt: 2,
    keys: [
      K(0, { fMouthO: 0 }),
      K(0.7, POSE.mouth, HR("flat"), { fMouthO: 0.8, headR: 5, fHappy: 0.6 }),
      K(1.1, POSE.mouth, HR("flat"), { fMouthO: 0.8, headR: 5, fHappy: 0.6 }),
      K(1.6, A.R(82, 82, 40, 10, -40), HR("open"), { fMouthO: 0, fHappy: 1, headR: 8 }),
      K(2.4, A.R(82, 82, 40, 10, -40), HR("open"), { fHappy: 1, headR: 8 }),
    ],
  },
  {
    name: "membentuk hati",
    aliases: ["membentuk hati", "bentuk hati", "tanda hati", "heart", "love", "cinta", "sayang", "saranghae", "aishiteru", "bikin hati", "love you", "suka kamu"],
    dur: 3.2,
    holdAt: 0,
    keys: [K(0, bothOf(POSE.heart, "heart"), { headR: 8, fHappy: 1, torsoP: -2 })],
    moods: ["Senang", "Malu"],
  },
  {
    name: "facepalm",
    aliases: ["facepalm", "menepuk dahi", "tepuk dahi", "pegang dahi", "memegang dahi", "pusing", "sakit kepala", "ya ampun deh", "speechless"],
    dur: 3,
    holdAt: 0,
    keys: [K(0, POSE.forehead, HR("flat"), { headP: 12, torsoP: 6, fSad: 0.3, fRelax: 0.3 })],
  },
  {
    name: "tangan di belakang",
    aliases: ["tangan di belakang", "menyembunyikan tangan", "tangan ke belakang", "hands behind back", "malu malu kucing", "polos", "pura pura polos"],
    dur: 3.2,
    holdAt: 0,
    keys: [K(0, bothOf(POSE.behind, "relax"), { torsoP: -3, headR: 6, fHappy: 0.5, shift: 0.4 })],
    moods: ["Malu", "Senang"],
    idle: 0.35,
  },
  {
    name: "menyatukan tangan",
    aliases: ["menyatukan tangan", "bersatukan tangan", "berdoa", "doa", "memohon", "mohon", "tolong", "please", "pray", "praying", "minta tolong", "permisi", "amin"],
    dur: 3,
    holdAt: 0,
    keys: [K(0, bothOf(POSE.pray, "flat"), { headP: 6, fRelax: 0.4, fSad: 0.12 })],
  },
  {
    name: "tangan di depan",
    aliases: ["tangan di depan", "menggenggam tangan", "genggam tangan", "tangan terlipat di depan", "sopan", "berdiri sopan", "clasp hands", "tangan bertaut", "polite"],
    dur: 5,
    holdAt: 0,
    keys: [K(0, bothOf(POSE.clasp, "soft"), { torsoP: 1, headR: 2, fRelax: 0.2 })],
    idle: 0.6,
  },
  {
    name: "mengusap rambut",
    aliases: ["mengusap rambut", "usap rambut", "mengibaskan rambut", "kibas rambut", "memainkan rambut", "mainkan rambut", "hair flip", "merapikan rambut", "rapikan rambut", "pegang rambut"],
    dur: 2.8,
    holdAt: 0,
    keys: [K(0, POSE.hairFlip, HR("relax"), { headR: -8, headY: -6, fHappy: 0.4 })],
    osc: [{ ch: "rWrist", amp: 8, hz: 1.6, from: 0.5 }],
    idle: 0.5,
  },
  {
    name: "menyelipkan rambut",
    aliases: ["menyelipkan rambut", "selipkan rambut", "selipkan rambut ke telinga", "tuck hair", "rambut ke belakang telinga", "mengaitkan rambut"],
    dur: 2.4,
    holdAt: 0,
    keys: [K(0, POSE.ear, HR("soft"), { headR: 7, headP: 3, fHappy: 0.35, fRelax: 0.3 })],
    idle: 0.8,
    moods: ["Malu", "Senang"],
  },
  {
    name: "menggaruk belakang kepala",
    aliases: ["menggaruk belakang kepala", "garuk tengkuk", "garuk belakang kepala", "scratch back head", "canggung", "awkward", "serba salah"],
    dur: 2.6,
    holdAt: 0,
    keys: [K(0, POSE.backHead, HR("claw"), { headR: 7, fHappy: 0.35, headP: 3 })],
    osc: [{ ch: "rPlane", amp: 7, hz: 4, from: 0.5 }],
    moods: ["Malu", "Bingung"],
  },
  {
    name: "menghentakkan kaki",
    aliases: ["menghentakkan kaki", "hentak kaki", "hentakkan kaki", "stomp", "stomping", "injak lantai", "kesal hentak", "ngambek hentak"],
    dur: 2.1,
    keys: [
      K(0, POSE.crossTop, POSE.crossLow, HR("soft"), HL("soft"), { fAngry: 0.5, headP: 3 }),
      K(0.2, { rLegFwd: 16, rKnee: 52 }),
      K(0.32, { rLegFwd: 4, rKnee: 3, torsoP: 3, headP: 5, hipsDY: -1.5 }),
      K(0.55, { rLegFwd: 16, rKnee: 52, hipsDY: 0 }),
      K(0.67, { rLegFwd: 4, rKnee: 3, torsoP: 3, headP: 5, hipsDY: -1.5 }),
      K(1.3, { rLegFwd: 0, rKnee: 0, hipsDY: 0 }),
    ],
    moods: ["Tsundere", "Marah"],
    shot: "full",
  },
  {
    name: "memainkan jari",
    aliases: ["memainkan jari", "mainkan jari", "mainin jari", "gelisah", "resah", "fidget", "fidgeting", "tidak tenang", "cemas", "khawatir", "nervous"],
    dur: 4.2,
    holdAt: 0,
    keys: [K(0, bothOf(POSE.clasp, "soft"), { headP: 6, gazeX: -10, gazeY: -6, fRelax: 0.3, fSad: 0.15 })],
    osc: [
      { ch: "lIdx", amp: 0.2, hz: 1.3, from: 0.4 },
      { ch: "rIdx", amp: 0.2, hz: 1.1, phase: 0.3, from: 0.4 },
      { ch: "rThumb", amp: 0.25, hz: 0.9, from: 0.4 },
      { ch: "lThumb", amp: 0.25, hz: 0.8, phase: 0.2, from: 0.4 },
    ],
    idle: 0.4,
    moods: ["Malu", "Sedih", "Bingung"],
  },
  {
    name: "bersandar",
    aliases: ["bersandar", "santai", "bersantai", "rileks", "relax pose", "leaning", "nyantai", "berdiri santai"],
    dur: 4.5,
    holdAt: 0,
    keys: [K(0, { shift: 0.9, hipsR: -3, torsoR: 2, headR: 4, hipsX: 1.5, fRelax: 0.3 }, A.R(40, 20, 50, -40), HR("relax"))],
    idle: 0.9,
    light: true,
  },
  {
    name: "menggoyang badan",
    aliases: ["menggoyang badan", "goyang badan", "bergoyang pelan", "mengayun", "sway", "swaying", "ayun badan", "berayun"],
    dur: 5,
    light: true,
    idle: 0.8,
    keys: [K(0, { fRelax: 0.2 })],
    osc: [
      { ch: "hipsR", amp: 3, hz: 0.3 },
      { ch: "hipsX", amp: 1.6, hz: 0.3, phase: 0.25 },
      { ch: "torsoR", amp: -2, hz: 0.3 },
      { ch: "headR", amp: 2, hz: 0.3, phase: 0.3 },
    ],
  },
  {
    name: "memutar bahu",
    aliases: ["memutar bahu", "putar bahu", "shoulder roll", "melemaskan bahu", "pegal"],
    dur: 1.8,
    light: true,
    idle: 0.8,
    keys: [
      K(0, { lShrug: 0, rShrug: 0 }),
      K(0.4, { lShrug: 11, rShrug: 3, torsoR: -1.5 }),
      K(0.9, { lShrug: 3, rShrug: 11, torsoR: 1.5 }),
      K(1.4, { lShrug: -2, rShrug: -2, torsoR: 0 }),
    ],
  },
  {
    name: "melompat kecil",
    aliases: ["melompat kecil", "loncat kecil", "loncat girang", "melonjak girang", "bounce", "bouncing", "senang banget", "girang", "kegirangan", "excited"],
    dur: 2.4,
    holdAt: 0,
    keys: [K(0, both(34, 40, 70, -10, "soft"), { fHappy: 1 })],
    osc: [
      { ch: "hipsDY", amp: 2.4, offset: 2.4, hz: 2.5, from: 0.3 },
      { ch: "crouch", amp: 0.07, offset: 0.07, hz: 2.5, from: 0.3 },
      { ch: "lRaise", amp: 8, hz: 2.5, from: 0.3 },
      { ch: "rRaise", amp: 8, hz: 2.5, from: 0.3 },
    ],
    idle: 0.3,
    moods: ["Senang"],
  },
  // ───────── beat (gerak spontan saat bicara) ─────────
  {
    name: "beat kanan",
    aliases: [],
    beat: true,
    dur: 1.3,
    light: true,
    inT: 0.22,
    outT: 0.4,
    keys: [K(0, A.R(30, 55, 62, 8), HR("relax")), K(0.35, A.R(40, 58, 78, 14), HR("open"), { headR: 2 }), K(0.7, A.R(34, 56, 66, 10), HR("relax"))],
  },
  {
    name: "beat dua tangan",
    aliases: [],
    beat: true,
    dur: 1.5,
    light: true,
    inT: 0.25,
    outT: 0.45,
    keys: [K(0, both(32, 40, 68, 8, "open", -50)), K(0.5, both(38, 44, 78, 12, "open", -55), { torsoP: -1.5 }), K(1, both(30, 40, 70, 8, "open", -50))],
  },
  {
    name: "beat telunjuk",
    aliases: [],
    beat: true,
    dur: 1.2,
    light: true,
    inT: 0.2,
    outT: 0.4,
    keys: [K(0, A.R(48, 80, 52, 4), HR("point")), K(0.3, A.R(56, 82, 40, 2), HR("point"), { headP: 2 }), K(0.6, A.R(48, 80, 52, 4), HR("point"))],
    moods: ["Serius", "Tsundere", "Marah"],
  },
  {
    name: "beat telapak",
    aliases: [],
    beat: true,
    dur: 1.4,
    light: true,
    inT: 0.25,
    outT: 0.45,
    keys: [K(0, A.R(36, 48, 85, 0, -65), HR("open")), K(0.5, A.R(40, 52, 78, 4, -70), HR("open"), { headR: 3 }), K(0.9, A.R(36, 48, 85, 0, -65), HR("open"))],
  },
];

/** Gerakan spontan saat diam. */
export const IDLE_MOTIONS = MOTIONS.filter((m) => (m.idle ?? 0) > 0);
export const BEAT_MOTIONS = MOTIONS.filter((m) => m.beat);
export const NAMED_MOTIONS = MOTIONS.filter((m) => !m.beat);
export const MOTION_BY_NAME = new Map(MOTIONS.map((m) => [m.name, m]));
